### ISSUE TITLE
framework.getWebexSDK() does not have phone object

### ISSUE THREAD

**Issue by redakker** [webex/webex-node-bot-framework#24]
The documentation sais:
framework.getWebexSDK() ⇒ object
Accessor for Webex SDK instance

I expected that is a full SDK due to the https://webex.github.io/webex-js-sdk/api/#nodejs was linked to this section.
I would like to use the Bot's phone to receive a call, or at least get the notification since I can call the Bot from the Webex Teams client.
Is this possible?

let webex = framework.getWebexSDK();
console.log(webex.phone);

The result is: undefined

**Comment by jpjpjp** [comment]
Hi @redakker.   The phone object in the Webex sdk is deprecated and replaced by the meeting object.   See https://developer.webex.com/docs/sdks/browser for details on how to use this object.

With that said, can you describe a bit more about what you are trying to achieve?   The Webex SDK provides a javascript wrapper around the messaging APIs as well as some interfaces that allow developers to embed Webex calling and meetings into a browser.

Most apps that use the framework are node.js based apps that do not run in a browser.  In order to use the SDK to make calls, it needs to be embedded in a browser so that the SDK can use the WebRTC methods in the browser.   In general Bots do not receive phone calls.
